name: AI Cognitive Analysis

on:
  workflow_run:
    workflows: ["Code Quality Analysis"]
    types: [completed]

permissions:
  contents: read
  pull-requests: write

jobs:
  ai-cognitive-analysis:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Get PR number
        id: pr-info
        run: |
          # For workflow_run, get PR info from the triggering workflow
          PR_NUMBER=$(gh pr list --head ${{ github.event.workflow_run.head_branch }} --json number --jq '.[0].number')
          PR_TITLE=$(gh pr view $PR_NUMBER --json title --jq '.title')
          PR_BODY=$(gh pr view $PR_NUMBER --json body --jq '.body')
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "pr_title<<EOF" >> $GITHUB_OUTPUT
          echo "$PR_TITLE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "pr_body<<EOF" >> $GITHUB_OUTPUT
          echo "$PR_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download quality analysis results
        uses: actions/download-artifact@v4
        with:
          name: code-quality-analysis-results
          path: ./quality-results/
        continue-on-error: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/requirements.txt
          # Install Azure AI dependencies for cognitive analysis
          pip install azure-ai-inference azure-identity

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.py
            **/*.js
            **/*.ts
            **/*.jsx
            **/*.tsx
            **/*.mjs
            **/*.cjs
            **/*.vue
            **/*.svelte
            **/*.java
            **/*.cs
            **/*.go
            **/*.rs
            sample-project/**/*.js
            sample-project/**/*.ts
            sample-project/**/*.jsx
            sample-project/**/*.tsx
          files_ignore: |
            **/*.md
            **/*.txt
            **/*.yml
            **/*.yaml
            **/*.json
            **/Dockerfile
            **/node_modules/**
            **/dist/**
            **/build/**

      - name: Analyze PR Cognitive Complexity
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AI_FOUNDRY_ENDPOINT: ${{ secrets.AI_FOUNDRY_ENDPOINT }}
          AI_FOUNDRY_MODEL: ${{ secrets.AI_FOUNDRY_MODEL }}
          AI_FOUNDRY_TOKEN: ${{ secrets.AI_FOUNDRY_TOKEN }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          PR_NUMBER: ${{ steps.pr-info.outputs.pr_number }}
        run: |
          python .code-analysis/scripts/run_cognitive_analysis.py
          echo "Cognitive complexity analysis complete"
        continue-on-error: true

      - name: Run AI Pre-Review Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AI_FOUNDRY_ENDPOINT: ${{ secrets.AI_FOUNDRY_ENDPOINT }}
          AI_FOUNDRY_MODEL: ${{ secrets.AI_FOUNDRY_MODEL }}
          AI_FOUNDRY_TOKEN: ${{ secrets.AI_FOUNDRY_TOKEN }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          PR_NUMBER: ${{ steps.pr-info.outputs.pr_number }}
        run: |
          python .code-analysis/scripts/ai_pre_review.py
          echo "AI-generated analysis for review triage (uses cognitive results)"
        continue-on-error: true

      - name: Run Intent Classification Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AI_FOUNDRY_ENDPOINT: ${{ secrets.AI_FOUNDRY_ENDPOINT }}
          AI_FOUNDRY_MODEL: ${{ secrets.AI_FOUNDRY_MODEL }}
          AI_FOUNDRY_TOKEN: ${{ secrets.AI_FOUNDRY_TOKEN }}
          PR_NUMBER: ${{ steps.pr-info.outputs.pr_number }}
        run: |
          python .code-analysis/scripts/intent_classifier.py \
            --repo . \
            --title "${{ steps.pr-info.outputs.pr_title }}" \
            --description "${{ steps.pr-info.outputs.pr_body }}" \
            --pr-output
          echo "AI-generated intent classification analysis"
        continue-on-error: true

      - name: Run Impact Prediction Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AI_FOUNDRY_ENDPOINT: ${{ secrets.AI_FOUNDRY_ENDPOINT }}
          AI_FOUNDRY_MODEL: ${{ secrets.AI_FOUNDRY_MODEL }}
          AI_FOUNDRY_TOKEN: ${{ secrets.AI_FOUNDRY_TOKEN }}
          PR_NUMBER: ${{ steps.pr-info.outputs.pr_number }}
        run: |
          python .code-analysis/scripts/impact_predictor.py \
            --repo . \
            --pr-title "${{ steps.pr-info.outputs.pr_title }}" \
            --pr-description "${{ steps.pr-info.outputs.pr_body }}" \
            --pr-output
          echo "AI-generated impact prediction analysis"
        continue-on-error: true

      - name: Generate Semantic Commit Story
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AI_FOUNDRY_ENDPOINT: ${{ secrets.AI_FOUNDRY_ENDPOINT }}
          AI_FOUNDRY_MODEL: ${{ secrets.AI_FOUNDRY_MODEL }}
          AI_FOUNDRY_TOKEN: ${{ secrets.AI_FOUNDRY_TOKEN }}
          PR_NUMBER: ${{ steps.pr-info.outputs.pr_number }}
        run: |
          python .code-analysis/scripts/semantic_commit_analyzer.py
          echo "AI-generated semantic commit story"
        continue-on-error: true

      # POST AI ANALYSIS COMMENTS IN PRIORITY ORDER
      - name: Post AI Pre-Review Comment (1st - Priority)
        if: always()
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ steps.pr-info.outputs.pr_number }}
        with:
          script: |
            const script = require('./.code-analysis/scripts/ai-pre-review-pr-comment.js');
            return await script({ github, context });

      - name: Post Cognitive Complexity Comment (2nd)
        if: always()
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ steps.pr-info.outputs.pr_number }}
        with:
          script: |
            const script = require('./.code-analysis/scripts/cognitive-analysis-pr-comment.js');
            return await script({ github, context });

      # Intent classification now integrated into AI pre-review comment
      # - name: Post Intent Classification Comment (3rd)
      #   if: always()
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       const script = require('./.code-analysis/scripts/intent-classification-pr-comment.js');
      #       return await script({ github, context });

      - name: Update PR Description with Semantic Story
        if: always()
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ steps.pr-info.outputs.pr_number }}
        with:
          script: |
            const script = require('./.code-analysis/scripts/semantic-commit-pr-description.js');
            return await script({ github, context });

      - name: Upload AI Analysis Results
        uses: actions/upload-artifact@v4
        with:
          name: ai-cognitive-analysis-results
          path: |
            ai_pre_review.json
            cognitive_analysis.json
            intent_classification.json
            impact_prediction.json
            semantic_commit_analysis.json
        if: always()
